services:
  app:
    build:
      context: .
    volumes:
      - ./.env:/var/config/.env
      - ./laravel:/var/www
    networks:
      - laravel
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - APP_ENV_PATH=/var/config
    restart: no

  nginx:
    build:
      context: ./nginx
    depends_on:
      app:
        condition: service_started
      certbot:
        condition: service_started
    volumes:
      - .:/var/www
      - ./certbot/www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
      - ./nginx/nginx.conf.template:/etc/nginx/conf.d/default.conf.template
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - laravel
    restart: no

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
