services:
  app:
    build:
      context: .
    volumes:
      - ./.env:/var/config/.env
      - ./laravel:/var/www
    networks:
      - laravel
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - APP_ENV_PATH=/var/config
    restart: no

  nginx:
    build:
      context: ./nginx
    depends_on:
      app:
        condition: service_started
    volumes:
      - .:/var/www
      - ./certbot/www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
      - ./nginx/nginx.conf.template:/etc/nginx/conf.d/default.conf.template
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - laravel
    restart: no

  certbot:
    image: certbot/certbot
    depends_on:
      nginx:
        condition: service_started
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet && echo 'Renewed'; sleep 12h & wait $!; done"
    restart: no

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel
    restart: no
    command: --max_connections=50 --innodb_buffer_pool_size=64M --key_buffer_size=16M --performance_schema=off
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ABSOLUTE_URI: /pma/
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - laravel
    restart: no

networks:
  laravel:

volumes:
  db_data:
  certbot-etc:
  certbot-var:
