version: "3.8"

services:
  app:
    build:
      context: .
    volumes:
      - ./.env:/var/config/.env
      - ./laravel:/var/www
    networks:
      - laravel
    environment:
      - APP_ENV_PATH=/var/config
    restart: always
    depends_on:
      - certbot

  nginx:
    image: nginx:alpine
    depends_on:
      - certbot
      - app
    volumes:
      - .:/var/www
      - ./nginx.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./nginx-entrypoint.sh:/usr/local/bin/nginx-entrypoint.sh
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
    entrypoint: /usr/local/bin/nginx-entrypoint.sh
    ports:
      - "80:80"
      - "443:443"
    networks:
      - laravel
    restart: always
    
  certbot:
    image: certbot/certbot
    environment:
      - CERTBOT_DOMAIN=${APP_DOMAIN}
      - CERTBOT_EMAIL=${APP_EMAIL}
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot-www:/var/www/certbot
      - ./certbot-entrypoint.sh:/usr/local/bin/certbot-entrypoint.sh
    entrypoint: /usr/local/bin/certbot-entrypoint.sh
    networks:
      - laravel
    restart: always

  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel
    restart: always
    command: --max_connections=50 --innodb_buffer_pool_size=64M --key_buffer_size=16M --performance_schema=off

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_ABSOLUTE_URI: /pma/
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data: